version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: pwd
      - run: docker run -t -v `pwd`:/app/test slowmybrosh/dietapp

workflows:
  tests:
    jobs:
      - build