version: 2.1

jobs:
  docker-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: docker run -e LOG_FILE=$LOG_FILE -e LOG_FOLDER=$LOG_FOLDER -t -v `pwd`:/app/test slowmybrosh/dietapp

workflows:
  tests:
    jobs:
      - docker-test