version: 2.1

jobs:
  docker-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: docker run -t -v `pwd`:/app/test slowmybrosh/dietapp -e LOG_DIR={$LOG_DIR} -e LOG_FOLDER={$LOG_FOLDER}

workflows:
  tests:
    jobs:
      - docker-test