version: 2.1

jobs:
  docker-test:
    docker:
       image: cimg/node:17.2.0
    steps:
      - checkout
      - run: pwd
      - run: docker run -t -v `pwd`:/app/test slowmybrosh/dietapp

workflows:
  tests:
    jobs:
      - docker-test