name: Updates README in dockerhub

on:
  push:
    branches:
      - main

jobs:
  update-README:
    runs-on: ubuntu-20.04
    steps:
      - name: Check code
        uses: actions/checkout@master
        
      - name: Update README      
        uses: meeDamian/sync-readme@v1.0.6
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}
          description: true
